### ISSUE TITLE
Question about code section

### ISSUE THREAD

**Issue by ghost** [ppalasek/linescan#1]
Hi @ppalasek , I have been working with your code for my project, and is awesome. I have been trying to understand the code and I would like to ask you if you could explain to me this part:

```
if (frame >= lineImage.cols) {
      lineImage.colRange(1, lineImage.cols - 1).copyTo(lineImage.colRange(0, lineImage.cols - 2));
      image.col(image.cols / 2).copyTo(lineImage.col(lineImage.cols - 2));
    }
    else {
      image.col(image.cols / 2).copyTo(lineImage.col(frame));
    }
```

I understand that `image.cols / 2` is the line that you are taking from the image and copy to the lineImage, but I can not understand the other part, why is that?

Daniel

**Comment by ppalasek** [comment]
Hi @danielTobon43 , nice to hear that you found the code interesting! It's been a while since I wrote this, but let's see if we can figure it out.

So we have an input image called `image` and the output image which we call `lineImage`, which we initialised at the beginning to 640 x 480 px:
`Mat lineImage = Mat::zeros(Size(640, 480), CV_8UC3);`

Inside the main, infinite loop we get a new `image` from the stream, resize it to 640x480px and we want to take the middle column from it and append it at the end of the `lineImage`. 

If the current frame index `frame` is smaller than the number of columns in `lineImage`, then just copy the middle column into column at position `frame` in `lineImage`. This is in the `else` part of the code you posted:
`image.col(image.cols / 2).copyTo(lineImage.col(frame));`

Otherwise, if the frame index is greater or equal to the number of columns of `lineImage`, it means that we have already filled the entire `lineImage` with `frame` number of columns. In that case, we move all the columns from index 1 until index `lineImage.cols - 1` into columns from index `0` until index `lineImage.cols - 2`, i.e. we just shift the whole image by 1 pixel to the left:
`lineImage.colRange(1, lineImage.cols - 1).copyTo(lineImage.colRange(0, lineImage.cols - 2));`
and copy the middle column to the end:
`image.col(image.cols / 2).copyTo(lineImage.col(lineImage.cols - 2)); // maybe this should be -1?`

Honestly, I'm not sure why I put `lineImage.cols - 2` instead of `lineImage.cols - 1` there, it could possibly be a bug. You can check when playing with it.

An example video of this is action can be found here:
https://www.youtube.com/watch?v=1X8DVp0Amh8

Hope this helps.

Petar

**Comment by ghost** [comment]
Hi, @ppalasek thanks for reaching out to me so quickly. Now I understand the process better. I got 3 more questions:

1. The shift movement of the image is just for the case where is a continuous stream right? because in case of a file the number of columns will be given by the number of frames in the video. 
2. I have developed something similar, but instead of getting a column of pixels, I used a region of interest and then, concatenate the frames. I am getting similar results, but with your project, the transition is smoothed since only use a column of pixels, so my question is regarding the final resolution of the output image. I saw you resize the input image and I avoided that to get the full image completely scanned (instead of that I resized the window of OpenCV to show the process). The thing is I am getting a low-resolution image at the end. My video file is 3820x2160px and 282 frames and the output image is 3820x282px. I know the width is given by the number of frames but the resolution is too low. 
3. Could be a way of initializing the output image without pre-defining the number of columns? this is because I could get empty frames and if that happens I will get an image with black spaces. Something similar when you initialize a list in python and just append the values to the end without predefining the size of the list.
